version: 0.2

env:
  variables:
    stage: "prod"
  parameter-store:
    config_json: "office-maker-profiles-config-prod"

    # public key for JWT should be same as office-maker-api's pubkey
    pubkey: "office-maker-api-authorizer-pubkey"

phases:
  install:
    commands:
      - echo ${config_json} >> config.prod.json
      - mkdir -p keys
      - echo "${pubkey}" >> keys/pubkey.pem
      - npm install
      - cd functions && npm install && cd -
      - npx sls dynamodb install --localPath .dynamodb
      - sudo apt-get update && sudo apt-get install -y openjdk-7-jre lsof
  pre_build:
    commands:
      - npm run test
  build:
    commands: |
      if [ "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/master" ]; then
        npx sls deploy -s ${stage}
      fi;

