version: 0.2

env:
  variables:
    stage: "prod"
  parameter-store:
    config_json: "office-maker-profiles-config-prod"

    # public key for JWT should be same as office-maker-api's pubkey
    pubkey: "office-maker-api-authorizer-pubkey"

phases:
  install:
    commands:
      - sudo apt-get update && sudo apt-get install -y lsof
      - npm i -g npm@latest
      - npm ci
      - cd functions && npm ci && cd -
      - wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O /usr/bin/jq && chmod +x /usr/bin/jq
      - pip install yq
      - pip install --upgrade awscli
      - docker pull amazon/dynamodb-local
      - echo ${config_json} >> config.json
      - mkdir -p keys
      - echo "${pubkey}" >> keys/pubkey.pem
  pre_build:
    commands:
      - docker run -d -p 8000:8000 amazon/dynamodb-local
      - echo $(npx sls print -s test | yq '.resources.Resources.ProfilesTable.Properties') > input.json && aws dynamodb create-table --cli-input-json file://input.json --endpoint-url "http://localhost:8000"
      - echo $(npx sls print -s test | yq '.resources.Resources.ProfilesSearchHelpTable.Properties') > input.json && aws dynamodb create-table --cli-input-json file://input.json --endpoint-url "http://localhost:8000"
      - echo $(npx sls print -s test | yq '.resources.Resources.ProfilesPostsTable.Properties') > input.json && aws dynamodb create-table --cli-input-json file://input.json --endpoint-url "http://localhost:8000"
      - aws --endpoint-url http://localhost:8000 dynamodb list-tables
      - npx mocha test/lambda-test.js

  build:
    commands: |
      if [ "$CODEBUILD_WEBHOOK_TRIGGER" = "branch/master" ]; then
        npx sls deploy -s ${stage}
      fi;

cache:
  paths:
    - '~/.npm/**/*'
